# ─────────────────────────────────────────────────────────────────────
# kernel/.cargo/config.toml
# NØNOS Cargo configuration with linker script
# - Bare-metal x86_64 with custom target JSON
# - Nightly build-std for core/alloc (no_std)
# - rust-lld, no-redzone, force frame pointers, tiny & auditable codegen
# - QEMU runner wired to `cargo run`
# ─────────────────────────────────────────────────────────────────────

# kernel/.cargo/config.toml
# NØNOS Cargo configuration with linker script

[build]
target = "x86_64-nonos.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-nonos]
rustflags = [
  "-C","panic=abort",
  "-C","relocation-model=static",
  "-C","code-model=kernel",
  "-C","lto=fat",
  "-C","embed-bitcode=yes",
  "-C","codegen-units=1",
  "-C","force-frame-pointers=yes",
  "-C","no-redzone=yes",
  "-C","symbol-mangling-version=v0",
  "-C","opt-level=z",
  "-Z","function-sections",
  "-Z","emit-stack-sizes",
  "-C","link-arg=-nostdlib",
  "-C","link-arg=-nostartfiles",
  "-C","link-arg=-static",
  "-C","link-arg=-z,relro",
  "-C","link-arg=-z,now",
  "-C","link-arg=-Tlinker.ld",  # Use our linker script
]

# Debug build flags
[target.'cfg(debug_assertions)']
rustflags = [
  "-Z","panic-abort-tests",
  "-Z","trap-unreachable=yes",
  "-C","overflow-checks=y",
  "-C","debug-assertions=y",
  "-C","debuginfo=1",
  "-Z","function-sections",
]

[target.'cfg(all())']
linker = "rust-lld"
runner = "../scripts/run-qemu.sh"

[env]
NONOS_RUNNER = "1"

[alias]
b  = "build"
br = "build --release"
r  = "run"
rr = "run --release"
ck = "check"
t  = "test"
