warn = ["clippy::all","clippy::perf","clippy::style","clippy::complexity","clippy::pedantic"]
allow = [
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc",
  "clippy::module_name_repetitions",
  "clippy::upper_case_acronyms"
]
