edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = true
hex_literal_case = "Upper"
