# .github/workflows/ci.yml
name: NØNOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src, llvm-tools-preview
    
    - name: Build kernel
      run: |
        cd kernel
        cargo build --target x86_64-nonos.json --release
    
    - name: Run tests
      run: cargo test --target x86_64-nonos.json
    
    - name: Build bootable image
      run: make img
    
    - name: Boot test in QEMU
      run: |
        timeout 30s qemu-system-x86_64 \
          -machine q35 \
          -m 512M \
          -nographic \
          -serial mon:stdio \
          -drive file=nonos.img,format=raw
