name: kernel-ci
on:
  push:
    paths: ["kernel/**", "boot/**", "scripts/**", ".github/workflows/kernel-ci.yml"]
  pull_request:
    paths: ["kernel/**", "boot/**", "scripts/**"]
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [dev, release]
    steps:
      - uses: actions/checkout@v4

      - name: rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, llvm-tools-preview, clippy, rustfmt

      - name: deps
        run: sudo apt-get update && sudo apt-get install -y lld qemu-system-x86 ovmf mtools

      - name: cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            kernel
            boot

      - name: clippy
        if: matrix.mode == 'dev'
        working-directory: kernel
        run: cargo clippy --no-deps -- -D warnings

      - name: build kernel
        working-directory: kernel
        run: cargo build ${{ matrix.mode == 'release' && '--release' || '' }}

      - name: build boot
        working-directory: boot
        run: cargo build ${{ matrix.mode == 'release' && '--release' || '' }}

      - name: package ESP
        run: |
          chmod +x scripts/run-qemu-cargo.sh
          ./scripts/run-qemu-cargo.sh || true

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nonos-esp-${{ matrix.mode }}
          path: |
            target/nonos_esp.img
            target/esp/**
